# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np





### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print("Numpy version:", np.__version__)


Numpy version: 2.3.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [6]:
a = np.random.random((2, 3, 5))
print("Array shape:", a.shape)
print("Array:")
print(a)

Array shape: (2, 3, 5)
Array:
[[[0.4950262  0.31206285 0.98017062 0.37088651 0.95818351]
  [0.80748475 0.94171264 0.07348718 0.68851517 0.28348414]
  [0.30199765 0.43593385 0.7701698  0.18858532 0.87153536]]

 [[0.99777682 0.46493591 0.89350984 0.58109543 0.69660979]
  [0.66883852 0.11393851 0.69015747 0.61619622 0.18543085]
  [0.62451798 0.84295061 0.99423199 0.02541933 0.08695653]]]



### 4. Print a.


In [9]:
print("Array a:")
print(a)


Array a:
[[[0.4950262  0.31206285 0.98017062 0.37088651 0.95818351]
  [0.80748475 0.94171264 0.07348718 0.68851517 0.28348414]
  [0.30199765 0.43593385 0.7701698  0.18858532 0.87153536]]

 [[0.99777682 0.46493591 0.89350984 0.58109543 0.69660979]
  [0.66883852 0.11393851 0.69015747 0.61619622 0.18543085]
  [0.62451798 0.84295061 0.99423199 0.02541933 0.08695653]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [10]:

b = np.ones((5, 2, 3))


### 6. Print b.


In [11]:
print("Array b :")
print(b)


Array b :
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [12]:
print("\nDo a and b have the same size")
print("a size:", a.size)
print("b size:", b.size)
print("Same size:", a.size == b.size)




Do a and b have the same size
a size: 30
b size: 30
Same size: True



### 8. Are you able to add a and b? Why or why not?


In [13]:
print("\nCan we add a and b?")
print("a shape:", a.shape)
print("b shape:", a.shape)
print("Addition possible?", a.shape == b.shape)
print("Reason:Array must have the same shape for element-wise addition")




Can we add a and b?
a shape: (2, 3, 5)
b shape: (2, 3, 5)
Addition possible? False
Reason:Array must have the same shape for element-wise addition




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [16]:
c = b.reshape(2, 3, 5)
print("\nTansposed b (variable c)shape:", c.shape)



Tansposed b (variable c)shape: (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [17]:
d = a + c

print("Addition successful ! d = a + c")
print("d shape:", d.shape)

print("\nWhy does it work now?")
print("a shape:", a.shape)
print("c shape:", c.shape)
print("b shape:", b.shape)
print("Because a and c have the same shape(2, 3, 5), but a and b had different shapes!")



Addition successful ! d = a + c
d shape: (2, 3, 5)

Why does it work now?
a shape: (2, 3, 5)
c shape: (2, 3, 5)
b shape: (5, 2, 3)
Because a and c have the same shape(2, 3, 5), but a and b had different shapes!



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [18]:
print("Array a:")
print(a)
print("\nArray d(a + c):")
print(d)

print("\nDifference and relation:")
print("Each value in d is exactly 1 greater than the corresponding value in a")
print("Because c was created from b (all ones), so d a + 1")



Array a:
[[[0.4950262  0.31206285 0.98017062 0.37088651 0.95818351]
  [0.80748475 0.94171264 0.07348718 0.68851517 0.28348414]
  [0.30199765 0.43593385 0.7701698  0.18858532 0.87153536]]

 [[0.99777682 0.46493591 0.89350984 0.58109543 0.69660979]
  [0.66883852 0.11393851 0.69015747 0.61619622 0.18543085]
  [0.62451798 0.84295061 0.99423199 0.02541933 0.08695653]]]

Array d(a + c):
[[[1.4950262  1.31206285 1.98017062 1.37088651 1.95818351]
  [1.80748475 1.94171264 1.07348718 1.68851517 1.28348414]
  [1.30199765 1.43593385 1.7701698  1.18858532 1.87153536]]

 [[1.99777682 1.46493591 1.89350984 1.58109543 1.69660979]
  [1.66883852 1.11393851 1.69015747 1.61619622 1.18543085]
  [1.62451798 1.84295061 1.99423199 1.02541933 1.08695653]]]

Difference and relation:
Each value in d is exactly 1 greater than the corresponding value in a
Because c was created from b (all ones), so d a + 1



### 12. Multiply a and c. Assign the result to e.


In [19]:
e = a * c
print("\nDoes e (a * c):")
print(e)



Does e (a * c):
[[[0.4950262  0.31206285 0.98017062 0.37088651 0.95818351]
  [0.80748475 0.94171264 0.07348718 0.68851517 0.28348414]
  [0.30199765 0.43593385 0.7701698  0.18858532 0.87153536]]

 [[0.99777682 0.46493591 0.89350984 0.58109543 0.69660979]
  [0.66883852 0.11393851 0.69015747 0.61619622 0.18543085]
  [0.62451798 0.84295061 0.99423199 0.02541933 0.08695653]]]




### 13. Does e equal to a? Why or why not?


In [20]:
print("\nDoes e equal a?")
print("Arrays are equal:",np.array_equal(e, a))
print("Why? because c contains all ones (1), so e = a x 1 = a")




Does e equal a?
Arrays are equal: True
Why? because c contains all ones (1), so e = a x 1 = a




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [21]:
d_max = np.max(d)
d_max = np.min(d)
d_mean = np.mean(d)

print(f"\nStatistics for array d:")
print(f"max: {d_max}")
print(f"mean:{d_mean}")




Statistics for array d:
max: 1.0254193295036687
mean:1.5653933776951967



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [23]:

f = np.empty((2, 3, 5))
print("Empty array f created with shape:", f.shape)
print("Initial values in f(uninitialized):")
print(f)

Empty array f created with shape: (2, 3, 5)
Initial values in f(uninitialized):
[[[1.4950262  1.31206285 1.98017062 1.37088651 1.95818351]
  [1.80748475 1.94171264 1.07348718 1.68851517 1.28348414]
  [1.30199765 1.43593385 1.7701698  1.18858532 1.87153536]]

 [[1.99777682 1.46493591 1.89350984 1.58109543 1.69660979]
  [1.66883852 1.11393851 1.69015747 1.61619622 1.18543085]
  [1.62451798 1.84295061 1.99423199 1.02541933 1.08695653]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [25]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(f"d_min: {d_min}, d_mean:{d_mean}, d_max: {d_max}")

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]

            if value == d_min:
                f[i, j, k] = 0
            elif value == d_mean:
                f[i, j, k] = 50
            elif value == d_max:
                f[i, j, k] = 100
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75
print("Array f populated with labels:")
print(f)                                


d_min: 1.0254193295036687, d_mean:1.5653933776951967, d_max: 1.9977768216066494
Array f populated with labels:
[[[ 25.  25.  75.  25.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  25.  75.  25.  75.]]

 [[100.  25.  75.  75.  75.]
  [ 75.  25.  75.  75.  25.]
  [ 75.  75.  75.   0.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [29]:
print("Array d:")
print(d)
print("\narray f:")
print(f)

print("\nDo we have the expected f?")
print("Unique values in f:",np.unique(f))
expected_values = [0, 25, 50, 75, 100]
print("Expected values:", expected_values)
print("Match:",set(np.unique(f)).issubset(expected_values))


Array d:
[[[1.4950262  1.31206285 1.98017062 1.37088651 1.95818351]
  [1.80748475 1.94171264 1.07348718 1.68851517 1.28348414]
  [1.30199765 1.43593385 1.7701698  1.18858532 1.87153536]]

 [[1.99777682 1.46493591 1.89350984 1.58109543 1.69660979]
  [1.66883852 1.11393851 1.69015747 1.61619622 1.18543085]
  [1.62451798 1.84295061 1.99423199 1.02541933 1.08695653]]]

array f:
[[[ 25.  25.  75.  25.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  25.  75.  25.  75.]]

 [[100.  25.  75.  75.  75.]
  [ 75.  25.  75.  75.  25.]
  [ 75.  75.  75.   0.  25.]]]

Do we have the expected f?
Unique values in f: [  0.  25.  75. 100.]
Expected values: [0, 25, 50, 75, 100]
Match: True


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.